server:
  port: 9010
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234


  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 814833551815-3lev3n1kj0vueh8fmai4qj7p9v5f9qok.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1153040985629219
            client-secret: a0ad5ceb145d1f1d6f8b2f45f6c9659a
            scope:
              - email
              - public_profile
          naver:
            client-id: ri3uN6R17HiuLV2kNRJF
            client-secret: z_7o_dJoaj
            scope:
              - name
              - email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9010/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌